language: R
r:
 - 3.4.0
# - release
 - devel # Incompatible with devtools
cache: packages
sudo: required # required if r_binary_packages; false otherwise
warnings_are_errors: true
r_check_args: --as-cran --no-manual # Workaround error compiling PDF manual

git:
  depth: 1

r_github_packages:
 - ms609/TreeSearch@noTreeDist
 - ms609/TreeDistData
# - r-lib/pkgload
# - r-lib/devtools

r_packages:
 - bookdown
 
r_binary_packages:
 - ape
 - covr
 - devtools
 - phangorn
 - Rdpack
 - roxygen2
 - testthat
 - vdiffr

before_script:
  - R -e "devtools::document()"

after_success:
  - Rscript -e "covr::codecov()"

before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
