language: r
r:
 - 3.4.0
 - devel
cache: packages
warnings_are_errors: true
r_check_args: --as-cran
   
git:
  depth: 5

r_binary_packages:
 - testthat
  
r_packages:
 - covr
 - devtools
 - memoise
 - R.cache
 - roxygen2
   
install:
 - R -e "install.packages('ape')"
 - R -e "install.packages('devtools')"
 - R -e "install.packages('phangorn')"
 - R -e "install.packages('roxygen2')"
 - R -e "install.packages('R.cache')"
 - R -e "install.packages('testthat')"
 - R -e "devtools::document()"
  
after_success:
  - Rscript -e "install.packages('covr'); covr::codecov()"