language: r
cache: packages
warnings_are_errors: false
#r_github_packages: KlausVigo/phangorn
repos: 
  ape: http://ape-package.ird.fr/
   
git:
  depth: 5

r_packages:
  devtools
install:
 - R -e "install.packages('ape', '.', repos = 'http://ape-package.ird.fr/')"
 - R -e "devtools::install_github('KlausVigo/phangorn', ref='1167f0be62f13cfad0fca8ae8224318c407195bf')"

# Needed for phangorn install?  
bioc_required: true
bioc_packages:
  - seqLogo
  - Biostrings