language: R
r:
 - 3.4.0
 - release
# - devel # Incompatible with devtools
cache: packages
sudo: required # required if r_binary_packages; false otherwise
warnings_are_errors: true
r_check_args: --as-cran
   
git:
  depth: 5
  
r_binary_packages:
 - ape
 - covr
 - devtools
 - memoise
 - phangorn
 - R.cache
 - Rdpack
 - roxygen2
 - testthat

before_script:
 - R -e "devtools::document()"
  
after_success:
  - Rscript -e "covr::codecov()"
  