language: R
r:
 - 3.4.0
# - release
 - devel # Incompatible with devtools
cache: packages
sudo: required # required if r_binary_packages; false otherwise
warnings_are_errors: true
r_check_args: --as-cran --no-manual # Workaround error compiling PDF manual

git:
  depth: 1

r_github_packages:
 - ms609/TreeSearch@noTreeDist
 - ms609/TreeDistData
# - r-lib/pkgload
# - r-lib/devtools

r_binary_packages:
 - ape
 - bookdown
 - covr
 - devtools
 - phangorn
 - Rdpack
 - roxygen2
 - testthat

before_script:
  - R -e "devtools::document()"

after_success:
  - Rscript -e "covr::codecov()"
  